return {
    "Astraea Guidance_None",
    "Blue Ninja Katana_Finisher",
    "Bubble Blaster_None",
    "Chroma Ninja Katana_Finisher",
    "Chroma Ninja Katana_None",
    "Dual Blossom Blades Emote_None",
    "Dual Leviathan Set_None",
    "Dual Loveclaw Blade_None",
    "Dual Nebula Blasters_Finisher",
    "Dual Nebula Blasters_None",
    "Festive Bow_None",
    "Firebloom Scythe Emote_None",
    "Floating Sword_None",
    "Green Ninja Katana_Finisher",
    "Moonflower Greatsword Emote_None",
    "Mummy's Curse_None",
    "Nebula Blade_None",
    "Red Ninja Katana_Finisher",
    "Resurrection Scythe_None",
    "Rocket Tree_None",
    "Runic Redblade_None",
    "Serpent's Cataclysm_None",
    "Shark_None",
    "Snow Globe_None",
    "Yin Yang Scythe_None",
}