return {
    "Arctic Waddle_None",
    "Astraea Staff_None",
    "Black Ninja Katana_None",
    "Bubble Blaster_None",
    "Calamity Guardian Emote_None",
    "Cat Paw Emote_None",
    "Chroma Ninja Katana_Finisher",
    "Dual Abyssal Set_None",
    "Dual Chroma Set Explosion_None",
    "Dual Divine Blaster_None",
    "Dual Nebula Blasters_None",
    "Dual Purity Blade_None",
    "Dual Rose Blade Emote_None",
    "Eclipse Gleam_None",
    "Forsaken Riftide_None",
    "Frostbound Lantern_None",
    "Harmonic Fan_None",
    "Hollow Oath Katana Emote_None",
    "Hollow Oath Katana_None",
    "Hollow Oath_None",
    "Mummy's Curse_None",
    "Nebula Blade_None",
    "Noob_None",
    "Pink Ninja Katana_None",
    "Polar Bear Emote_None",
    "Polar Bear Pop_None",
    "Prismatic Odachi Emote_None",
    "Prismatic Odachi Explosion_None",
    "Pure Power_None",
    "Purity Blade_None",
    "Resurrection Scythe Emote_None",
    "Serpent's Cataclysm_None",
    "Shark_None",
    "Shatterflight Bird_None",
    "Snowball Launcher_None",
    "Yin Yang Scythe_None",
}