return {
    "Cat Paw Emote_None",
    "Cat Paw_None",
    "Chroma Ninja Katana_Finisher",
    "Chroma Scythe_None",
    "Dual Kraken Scythe Emote_None",
    "Dual Nebula Blasters_None",
    "Floppy Chicken_None",
    "Forsaken Riftide_None",
    "Hollow Oath Katana Emote_None",
    "Hollow Oath Katana_None",
    "Noob_None",
    "Paw Punch_None",
    "Pink Ninja Katana_Finisher",
    "Pink Ninja Katana_None",
    "Red Ninja Katana_Finisher",
    "Serpent Emote_None",
    "Shark_None",
    "Thorned Sovereign_None",
    "Yin Yang Scythe_None",
}